module.exports=[
   "In Search of Lost Time",
   "Ulysses",
    "Don Quixote",
    "One Hundred Years of Solitude",
    "The Great Gatsby",
    "Moby Dick",
    "War and Peace",
    "Hamlet",
    "The Odyssey",
    "Madame Bovary",
    "The Divine Comedy",
    "Lolita",
    "The Brothers Karamazov",
    "Crime and Punishment",
   "Wuthering Heights",
    "The Catcher in the Rye",
   "Pride and Prejudice",
    "The Adventures of Huckleberry Finn",
   "Anna Karenina",
   "The Iliad",
   "To the Lighthouse",
   "Catch-22",
   "Heart of Darkness",
   "The Sound and the Fury",
   "Nineteen Eighty Four",
   "Great Expectations",
   "The Grapes of Wrath",
   "Absalom, Absalom!",
   "Invisible Man",
   "To Kill a Mockingbird",
   "The Trial",
   "The Red and the Black",
   "Middlemarch",
   "Gulliver's Travels",
   "Beloved",
  "Mrs. Dalloway",
   "The Stories of Anton Chekhov",
  "The Stranger",
   "Jane Eyre",
   "The Aeneid",
   "Collected Fiction",
   "The Sun Also Rises",
   "David Copperfield",
   "Tristram Shandy",
   "Leaves of Grass",
   "The Magic Mountain",
   "Midnight's Children"
];